name: Enviar Mensaje

on:
  schedule:
    # Programado para ejecutarse a las 19:50 hora de Chile (23:50 UTC en horario de invierno UTC-4)
    - cron: '50 23 * * *'

jobs:
  enviar-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Copiar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python script.py
